### ISSUE TITLE
"Creating Notes" page missing?

### ISSUE THREAD

**Issue by cansar** [mwharton3/zettelmin#1]
Hi,

I just tried out the vault and when I clicked the link it created a default page. I think you may not have checked it in?

Thanks!

**Comment by mwharton3** [comment]
Hey @cansar thanks for the issue submission.

I just tried cloning a fresh copy and didn't see issues. My steps:
- Clone repo
- Open folder as vault
- When prompted, turn off safe mode
- `ctrl + E` to render the daily notes page (which should pop up first)
- Click "Create Note" button at the top

At this point, a new note with the `templates/Default Note` template pops up in the `notes/` folder undrendered.

Can you try these steps and let me know what happens?

**Comment by cansar** [comment]
Sorry if that was unclear - that part works great. The "[[Creating Notes]]" page is missing, referenced in e.g. "See [[Creating Notes]] and [[Syncing Vaults Across Devices]]." on the README page. I thought it had more meta information about when to use which note type, etc.

**Comment by mwharton3** [comment]
Ah, got it. That should be fixed now.

Closing the issue, but feel free to open back up or make a new one if you find something else.
